# Your Wi-Fi SSID and password
wifi_ssid: "WiFI-Name"
wifi_password: "xxxxTOPSECRETxxxx"

# Keys Magical Weasly Clock
magicclock_ApiKey: "++YOUR_APIKEY_FROM_ESPHOME++"
magicclock_OtaSecret: "++YOUR_OTA_SECRET_FROM_ESPHOME++"
magicclock_wg_endpoint: "wireguardendpoint.your_domain.net"
magicclock_privatekey: "++PRIVATE_KEY-FROM_WIREGUARD_CONFIG++"
magicclock_publickey: "++PUBLIC_KEY-FROM_WIREGUARD_CONFIG++"
magicclock_presharedkey: "++PRESHARED_KEY-FROM_WIREGUARD_CONFIG++"